name: Deploy App to AKS

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.AZ_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZ_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZ_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZ_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: aks
        run: terraform init

      - name: Terraform Plan
        working-directory: aks
        id: plan
        run: terraform plan
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        working-directory: aks
        run: terraform apply -auto-approve
        
      - name: Get Cluster Name
        working-directory: aks
        run: |
          cluster=$(terraform output -raw kubernetes_cluster_name)
          echo $cluster
          
      - name: Terraform Destroy
        working-directory: aks
        run: terraform destroy -auto-approve

