name: EKS Remote State Backend 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-2
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: eks-backend
        run: terraform init

      - name: Terraform Validate
        working-directory: eks-backend
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        working-directory: eks-backend
        run: terraform plan -no-color

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        working-directory: eks-backend
        run: terraform apply -auto-approve
