name: Check GKE Health

on:
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: read
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_ID_PROVIDER }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    
    - name: Terraform Init
      working-directory: gke
      run: terraform init -upgrade

    - id: 'gcloud'
      name: 'gcloud'
      working-directory: gke
      run: |-
        gcloud components install gke-gcloud-auth-plugin
        gcloud container clusters get-credentials $(terraform output -raw kubernetes_cluster_name) --region=us-central1
        kubectl get nodes
        kubectl get pods
        kubectl get services
